health_base:
  target: dev
  outputs:
    dev:
      type: postgres
      host: healthcare-postgres
      user: postgres
      password: passwad
      port: 5432
      dbname: health_data
      schema: dbt_health
      threads: 4