{
 "title": "Healthcare Facilities",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Last 5 conversations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  question,\r\n  answer,\r\n  relevance\r\nFROM conversations\r\nORDER BY timestamp DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Feedback",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  SUM(CASE WHEN feedback > 0 THEN 1 ELSE 0 END) as thumbs_up,\r\n  SUM(CASE WHEN feedback < 0 THEN 1 ELSE 0 END) as thumbs_down\r\nFROM feedback\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo() "
    }
   ]
  },
  {
   "title": "Relevancy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  relevance,\r\n  COUNT(*) AS count \r\nFROM conversations \r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo() \r\nGROUP BY relevance"
    }
   ]
  },
  {
   "title": "Model used",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  model_used,\r\n  COUNT(*) as count \r\nFROM conversations\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo() \r\nGROUP BY model_used"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp AS time,\r\n  response_time\r\nFROM conversations\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Openai cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp AS time,\r\n  openai_cost\r\nFROM conversations \r\nWHERE openai_cost > 0\r\nORDER BY openai_cost"
    }
   ]
  },
  {
   "title": "Token usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp AS time,\r\n  total_tokens\r\nFROM conversations\r\nORDER BY timestamp"
    }
   ]
  }
 ]
}