{
 "title": "Healthcare Facilities",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp AS time,\r\n  response_time\r\nFROM conversations\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Model used",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  model_used,\r\n  COUNT(*) as count \r\nFROM conversations\r\nGROUP BY model_used"
    }
   ]
  },
  {
   "title": "Relevance count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  relevance,\r\n  COUNT(*) AS count \r\nFROM conversations \r\nGROUP BY relevance"
    }
   ]
  },
  {
   "title": "Openai cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp AS time,\r\n  openai_cost\r\nFROM conversations \r\nORDER BY openai_cost"
    }
   ]
  },
  {
   "title": "Token usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp AS time,\r\n  total_tokens\r\nFROM conversations\r\nORDER BY timestamp"
    }
   ]
  }
 ]
}